language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - pip install -e .
  - pip install -r .travis-requirements.txt
# command to run tests
script:
  coverage run --source=gunstar runtests.py
after_success:
  coveralls
